<!--NAVIGATION-->

<a href="https://colab.research.google.com/github/bpesquet/machine-learning-katas/blob/master/data/Tensor_Management.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open in Google Colaboratory"></a>


# Kata: Tensor Management

## Instructions

This is a self-correcting exercise generated by [nbgrader](https://github.com/jupyter/nbgrader). 

Complete the cells beginning with `# YOUR CODE HERE` and run the subsequent cells to check your code.

## Part 1: Tensor Basics

In [1]:
# Import NumPy
import numpy as np

### Question

Create a 2D tensor (a matrix) with dimensions (3,4) containing integer values of your choice. Store this tensor in a variable named `x`.

In [2]:
# YOUR CODE HERE
x = np.arange(12).reshape(3,4)

In [3]:
print(x)
# Assert dimensions
assert x.ndim == 2
assert x.shape == (3, 4)
# Assert data type 
assert issubclass(x.dtype.type, np.integer)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Question

Update the shape of the previous tensor so that it has dimensions (6,2).

In [4]:
# YOUR CODE HERE
x = x.reshape(6,2)

In [5]:
print(x)
# Assert tensor dimensions
assert x.ndim == 2
assert x.shape == (6, 2)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


### Question

Change the type of the previous tensor values to `float32`.

In [6]:
# YOUR CODE HERE
x = x.astype(float)

In [7]:
print(x)
# Assert data type
assert issubclass(x.dtype.type, np.floating)

[[ 0.  1.]
 [ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]
 [ 8.  9.]
 [10. 11.]]


### Question

Normalize the previous tensor so that it has a mean of 0 and a standard deviation of 1 on its first axis.

In [28]:
# YOUR CODE HERE
x = (x - x.mean(axis=0)) / x.std(axis=0)

In [29]:
print(x)
x_mean = x.mean(axis=0)
x_std = x.std(axis=0)
# Assert mean
assert np.abs(np.max(x_mean)) < 10**-6
# Assert standard deviation
assert np.abs(np.max(x_std-1)) < 10**-6

[-0.20974004 -0.65970511 -0.61862457 -0.93200586 -1.00490384  0.73455302
 -0.97242241 -0.20521349 -1.34009592 -0.77645438 -0.81510636  1.53605209
 -0.91713999 -1.23155526  1.43539602 -0.1921382   0.95545389  1.44489672
  1.2969266  -1.08403417 -1.44014497  0.237728    0.75361437  1.58599641
 -0.579191    0.95403392  1.28674717 -0.39152547 -1.71863948 -0.98685393
 -1.50001966  1.24645446 -1.72355608  0.83298625 -1.42019107  0.54721083
  1.09639224 -1.65749156 -0.4846381   1.61326192 -0.27202952  0.30449704
 -0.52960606  1.04039974 -1.42140996 -1.70895808  1.54843854 -1.14366149
  1.22227693  1.54261808 -0.41018545 -1.76560007  0.42299977  1.33652563
  0.04382798  0.47860301  0.10713152  1.36399535  1.64244184  1.04549954
 -1.60207928  0.71902047  0.32783793  0.60739173  0.58836706 -1.12016228
 -1.43588314  0.39985011  1.30986285  0.45080551 -1.76147208 -1.44680411
  1.18109437  0.17907225 -0.94002735 -1.46188092 -0.16037469 -1.51613296
 -1.35287801  1.13843967  0.65267899  1.51845367  0

## Part 2: One-hot Encoding

In [30]:
from keras.utils import to_categorical

# Definition of a 1D tensor (vector)
tensor = np.array([3, 1, 0, 2, 1])

### Question

Encode the previous tensor into the `x` variable, following a binary representation (`one-hot encoding`).

In [ ]:
# YOUR CODE HERE


In [ ]:
print(x)
# Assert one-hot encoding
assert x.shape == (5, 4)
assert np.array_equal([0,0,0,1], x[0])
assert np.array_equal([0,1,0,0], x[1])
assert np.array_equal([1,0,0,0], x[2])
assert np.array_equal([0,0,1,0], x[3])
assert np.array_equal([0,1,0,0], x[4])

## Part 3: Image Management

In [ ]:
import matplotlib
import matplotlib.pyplot as plt
from sklearn.datasets import load_sample_images
# Display plots inline and change plot resolution to retina
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

In [ ]:
# Load samples images
images = np.asarray(load_sample_images().images)
print(f'Number of images: {len(images)}. Images tensor: {images.shape}')

first_image = images[0]
# Display first image
plt.imshow(first_image)

# Print details about first image
print(f'First image: {first_image.shape}')

### Question

Store in variables respectively named `rgb_values_topleft` and `rgb_values_bottomright` the RGB values of the top-left and bottom-right pixels of the first image.

In [ ]:
# YOUR CODE HERE

In [ ]:
print(f'Top-left pixel: {rgb_values_topleft}')
assert rgb_values_topleft.shape == (3,)
print(f'Bottom-right pixel: {rgb_values_bottomright}')
assert rgb_values_bottomright.shape == (3,)

### Question

Reshape the previous `images` tensor into a 2D tensor.

In [ ]:
# YOUR CODE HERE

In [ ]:
# Assert new tensor dimensions
assert images.shape == (2, 819840)
# Assert RGB values of top-left in first image
assert np.array_equal(rgb_values_topleft, images[0,:3])
# Assert RGB values of bottom-right pixel in first image
assert np.array_equal(rgb_values_bottomright, images[0,819837:])